t3n:
  SEO:
    Routing:
      redirect:
        enable:
          trailingSlash: true
          toLowerCase: false
        statusCode: 301
      blacklist:
        '/neos/.*': true

Neos:
  Flow:
    http:
      chain:
        process:
          chain:
            routing:
              component: 't3n\SEO\Routing\RoutingComponent'
