t3n:
  SEO:
    Routing:
      redirect:
        enable: true
        statusCode: 303
        toLowerCase: false
      blacklist:
        '/neos/.*': true

Neos:
  Flow:
    http:
      chain:
        process:
          chain:
            routing:
              component: 't3n\SEO\Routing\RoutingComponent'
